### ISSUE TITLE
Database Connection Failed 

### ISSUE THREAD

**Issue by yellow-starburst** [DefensiveOrigins/PlumHound#1]
Used the correct username and password in arguements and also uncommented the first section of the script to include username, password and database url.
Still Gave me the error "Database Connection Failed"

**Comment by yellow-starburst** [comment]
https://twitter.com/mcohmi/status/1261038277743656961?s=21

**Comment by peterhgombos** [comment]
This can be fixed by adding "encrypted=False" to the database connection. This could also be added as a command line option.

**Comment by Relkci** [comment]
@peterhgombos @yellow-starburst  Implemented --UseEnc to set Encryption = True.  Omit --UseEnc to default as False.

c89687f07532af0677648234bc471f7fe8310bb2

@yellow-starburst  Please test with and withouth --UseEnc flag

**Comment by yellow-starburst** [comment]
> This can be fixed by adding "encrypted=False" to the database connection. This could also be added as a command line option.
Thank you for your help!
