### ISSUE TITLE
CSV output_type error

### ISSUE THREAD

**Issue by yellow-starburst** [DefensiveOrigins/PlumHound#3]
**Describe the bug**
Changed default tasks output to be CSV.
Turned verbose to 1000 max and no errors when running query. Says that the file has been created
When I check the default location of there isn't any csv output.

**Comment by Relkci** [comment]
CSV output had some syntax issues. 

updated da0550b043d128ebf75b6d41bbe4a96caa9b8a03

test with:
```
python3.8 PlumHound.py -c "MATCH (n:User) RETURN n.name, n.displayname, n.description, n.title, n.pwdneverexpires, n.passwordnotreqd, n.sensitive, n.admincount, n.serviceprincipalnames" --ox "CSV" -v 1000 -t "CSV-GPO Test" --of "test.csv"
python3.8 PlumHound.py -x tasks/default-csv.tasks
```

Please confirm and close

Thanks

Kent

**Comment by yellow-starburst** [comment]
Thanks again Kent!
