### ISSUE TITLE
CSV Column title - Writing in several instead of just 1

### ISSUE THREAD

**Issue by yellow-starburst** [DefensiveOrigins/PlumHound#4]
Noticed a bug in CSV:
The problem is that each character of the title is being written to a new column instead of just one column. The  format of the column title is the following:

c | . | n | a | m | e
-- | -- | -- | -- | -- | --

**Comment by Relkci** [comment]
ack and confirmed -- will resolve on next push , hopefully this week

**Comment by Relkci** [comment]
a002b11228955f285a5ae62623c12d1e861996e2

Updated.  Column Headers needed to be passed in as a list of lists, as opposed to list of str. Please confirm update resolved and close.  @yellow-starburst
