### ISSUE TITLE
Queries not returning results

### ISSUE THREAD

**Issue by yellow-starburst** [DefensiveOrigins/PlumHound#5]
Disclaimer: May be a false positive
Noticed that 2 files does not contain any data. 

- Shortest Path DA
-  Permissions Everyone
Currently reviewing to discover a potential cause

**Comment by Relkci** [comment]
ack and confirmed --

Removed Shortest Path from default.tasks for the time being. 
I ran on a much larger dataset tonight, confirmed both of these are not producing results as expected.  Will review on the large dataset and find correction.  Both issues are with the related  cypher queries and not the .py
