### ISSUE TITLE
Output format selections don't seem to function

### ISSUE THREAD

**Issue by iditabad** [DefensiveOrigins/PlumHound#8]
**Describe the bug**
The --OutFile or --ox options don't seem to work.

**To Reproduce**
1. python PlumHound.py -p "bloodhound" -x tasks/default.tasks --OutFormat CSV
(Get output in HTML)

Alternatively:
1. python PlumHound.py -p "bloodhound" -x tasks/default.tasks --ox CSV
(Get output in HTML still)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/28488957/83292407-09482980-a1b8-11ea-806a-7f82a5971bd9.png)

**Desktop (please complete the following information):**
 - OS: W10
- Python 3.8 downloaded and installed today

**Additional context**

**Comment by yellow-starburst** [comment]
Root cause - default.tasks must be changed. Fortunately Relkci created an example with the file  "default-csv.tasks".
I believe the "--OutFormat CSV" or "-oX" is meant to act as an output for a single query. 
Hope this helps :)

**Comment by Relkci** [comment]
Confirmed documentation issue.
--ox is disregarded if -x is used with a tasklist.  the output type is specified directly in the tasklist if it a tasklist is used. 
TODO: clarify documentation, configure Argparse to reject -x and --ox combinations

**Comment by Relkci** [comment]
Updated for clarification in 15c647b520e67294e020e60362378398c5815d1d
